[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "house_price"
version = "0.0.1"
description = "Obtener precios de casas"
authors = [
  { name = "Grupo 1" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.10.20"


[tool.ruff]
line-length = 99
src = ["house_price"]
include = ["pyproject.toml", "house_price/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["house_price"]
force-sort-within-sections = true

